# fly.toml app configuration file generated for wdp-recommendation-system-dq-taq on 2025-06-28T05:49:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wdp-recommendation-system-dq-taq'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
